## WiSHFUL Agent config file

agent_info:
    name: 'contiki_control_agent'
    info: 'WiSHFUL example Contiki control agent'
    iface: 'eth0'

modules:
    discovery:
        module : wishful_module_discovery_pyre
        class_name : PyreDiscoveryAgentModule
        kwargs: {"iface":eth0, "groupName":"wishful_contiki"}
    gitar_engine:
        module : wishful_module_gitar
        class_name : GitarEngine
        interfaces : ['lowpan0', 'lowpan1', 'lowpan2', 'lowpan3']
        kwargs : {'GitarConfig' : './examples/contiki/config/portable/gitar.ini','SupportedInterfaces' : ['lowpan0', 'lowpan1', 'lowpan2', 'lowpan3'],'ControlExtensions' : {'taisc' : './examples/contiki/taisc_control_extensions.csv', 'rime' : './examples/contiki/rime_control_extensions.csv'}}
    taisc_connector:
        module : wishful_module_taisc
        class_name : TAISCConnector
        interfaces : ['lowpan0', 'lowpan1', 'lowpan2', 'lowpan3']
        kwargs : {'RadioPrograms' : {"CSMA":0,"TDMA":2,"TSCH":1}}
    rime_connector:
        module : wishful_module_rime
        class_name : RIMEConnector
        interfaces : ['lowpan0', 'lowpan1', 'lowpan2', 'lowpan3']
