## WiSHFUL Local Control Porgram config file

agent_info:
    name: 'contiki_local_control'
    info: 'Example Contiki local control program'
    iface: 'lo'

modules:
    gitar_engine:
        module : wishful_module_gitar
        class_name : GitarEngine
        interfaces : ['lowpan0','lowpan1','lowpan2','lowpan3']
        kwargs : {'GitarConfig' : './examples/contiki/config/portable/gitar.ini','SupportedInterfaces' : ['lowpan0'],'ControlExtensions' : {'taisc' : './examples/contiki/taisc_control_extensions.csv', 'rime' : './examples/contiki/rime_control_extensions.csv'}}
    taisc_connector:
        module : wishful_module_taisc
        class_name : TAISCConnector
        interfaces : ['lowpan0']
        kwargs : {'RadioPrograms' : {"CSMA":0,"TDMA":2,"TSCH":1}}
    rime_connector:
        module : wishful_module_rime
        class_name : RIMEConnector
        interfaces : ['lowpan0']
