## WiSHFUL Local Control Program config file

agent_info:
    name: 'contiki_local_controller'
    info: 'Example Contiki local control program'
    iface: 'lo'
    ##interfaces : ['wlan0','lo']

modules:
    ## Copied from control_agent_config.yaml:: Works Ok
    discovery:
        module : wishful_module_discovery_pyre
        class_name : PyreDiscoveryAgentModule
        kwargs: {"iface":lo, "groupName":"wishful_contiki"}
                
    simple:
        module : wishful_module_simple
        class_name : SimpleModule2
        interfaces : ['lo', 'wlan0', 'wlan1', 'eth0']


    #gitar_engine:
    #    module : wishful_module_gitar
    #    class_name : GitarEngine
    #    interfaces : ['lowpan0']
    #    kwargs : {'GitarConfig' : './examples/contiki/config/localhost/gitar.ini','SupportedInterfaces' : ['lowpan0'],'ControlExtensions' : {'taisc' : './examples/contiki/taisc_control_extensions.csv', 'rime' : './examples/contiki/rime_control_extensions.csv'}}
    #taisc_connector:
    #    module : wishful_module_taisc
    #    class_name : TAISCConnector
    #    interfaces : ['lowpan0']
    #    kwargs : {'RadioPrograms' : {"CSMA":0,"TDMA":2,"TSCH":1}}
    #rime_connector:
    #    module : wishful_module_rime
    #    class_name : RIMEConnector
    #    interfaces : ['lowpan0']
